require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'eating_journal' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


  target 'eating_journalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  # Permission handler
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
end

target 'eating_journal-tvOS' do
  # Pods for eating_journal-tvOS

  target 'eating_journal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_native_modules!
